### ISSUE TITLE
Issue printing after installing TLC printers

### ISSUE THREAD

**Issue by davidcorbin** [ShaunJorstad/gcc-nix#2]
Had an issue when trying to print after running the install script:

<img width="1092" alt="Screen Shot 2019-08-08 at 8 53 57 PM" src="https://user-images.githubusercontent.com/5752872/62746706-03ae0700-ba1f-11e9-8b39-d788360c7d1f.png">
<img width="1092" alt="Screen Shot 2019-08-08 at 8 54 56 PM" src="https://user-images.githubusercontent.com/5752872/62746707-03ae0700-ba1f-11e9-8284-2409bd8dcc7c.png">

**Comment by ShaunJorstad** [comment]
I saw this again on a student's laptop. The macbook was brand new, I had him sign into the app store and restart. The issue did not reoccur, but I don't have access to anything running MacOS so i'm unsure if signing into the app store was necessary.

**Comment by ShaunJorstad** [comment]
I have run the install script on about 10 macbooks. After doing so, the first time the macbook prints to either GCCBW or GCCColor, that update dialogue pops up. Are you aware of what is being updated? 
Something odd that I have found, is that whatever is being updated installs much faster on older generation macbooks.

**Comment by davidcorbin** [comment]
I'm not sure what's going on. I presume that the printer requires newer HP printer drivers. Eventually the necessary software installed and printing began working for me. I'm not sure that we could automate installing the correct drivers but I'll look into it.

**Comment by ShaunJorstad** [comment]
The drivers that i have linked (the .ppd files) were up to date when I wrote the script but I wasn't experiencing the second download/install so that may be the case. After the script finishes executing on the next macbook, I'll copy their installed .ppd files and compare it with what is installed via the script.

**Comment by ShaunJorstad** [comment]
> I'm not sure what's going on. I presume that the printer requires newer HP printer drivers. Eventually the necessary software installed and printing began working for me. I'm not sure that we could automate installing the correct drivers but I'll look into it.

If you are able to compare your installed .ppd files with what is in the script that would also work. I don't remember where I found the drivers.

**Comment by davidcorbin** [comment]
Gotcha I'll look into it. Not sure where drivers are stored on mac either.

**Comment by davidcorbin** [comment]
<img width="612" alt="Screen Shot 2019-09-03 at 1 03 54 PM" src="https://user-images.githubusercontent.com/5752872/64193804-8a51da80-ce4b-11e9-8e33-19059a59fc0c.png">

Didn't find the .ppd files but found the version of the drivers: 19.13
